# Generated by Django 3.1.5 on 2021-01-18 03:11

import askcompany.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to=askcompany.utils.uuid_upload_to),
        ),
    ]
