# Generated by Django 3.1.5 on 2021-01-18 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_func(apps, schema_editor):
    # 현재 있는 모든 user에 대해서 profile 만들어주기
    # migrations에서는 apps.get_model을 통해 관련 user객체를 얻어와야함.
    # RunPython 및 askcompany 중급 6강 참고
    auth_user_model = settings.AUTH_USER_MODEL.split(',')
    User = apps.get_model(*auth_user_model)
    Profile = apps.get_model('accounts', 'Profile')

    for user in User.objects.all():
        print('create profile for user#{}'.format(user.pk))
        Profile.objects.create(user=user)
        # 다른 요소를 안 넣어도 되는 이유는 blank=True이기 떄문


def backward_func(apps, schema_editor):
    pass
# backward는 할 필요가 없는 게, 어차피 역방향으로 가면 one to one이니 날릴 것.


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # Profile migrate할 때 기존 user에 profile 추가하기 위함
        migrations.RunPython(forward_func, backward_func),
    ]
